name: finloop
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  get_it: ^9.1.1
  injectable: ^2.3.2
  go_router: ^17.0.0

  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0

  flutter_neumorphic_plus: ^3.0.3
  google_fonts: ^6.3.2
  fl_chart: ^1.1.1
  font_awesome_flutter: ^10.6.0
  percent_indicator: ^4.2.3

  intl: ^0.20.2
  uuid: ^4.2.1
  shared_preferences: ^2.2.2
  animate_do: ^4.2.0
  flutter_dotenv: ^6.0.0
  flutter_localization: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - .env
    - assets/image/
    - assets/logo/